all: tree.svg tree-chain.svg tree-team.svg
tree.svg: tree.dot
	dot -Tsvg tree.dot > tree.svg
tree-chain.svg: tree-chain.dot
	dot -Tsvg tree-chain.dot > tree-chain.svg
tree-team.svg: tree-team.dot
	dot -Tsvg tree-team.dot > tree-team.svg
